### PR TITLE
Fix styles import

### PR DESCRIPTION
**Pull request by fdionisi**

### CODE REVIEW

**Comment by kzima** [comment]
those dependencies are handled on js level:
https://github.com/kzima/vuestrap/blob/master/components/button-group/index.js
https://github.com/kzima/vuestrap/blob/master/components/carousel/index.js

**Comment by fdionisi** [comment]
The problem is when you try to build vuestrap-base-components.
It give this error:

```
ERROR in ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./~/vuestrap-theme-loader!./~/vuestrap/bootstrap/_button-group.scss
Module build failed:

                      ^
      ".btn-group-sm > .btn" failed to @extend ".btn-sm".
The selector ".btn-sm" was not found.
Use "@extend .btn-sm !optional" if the extend should be able to fail.
      in ~/vuestrap-base-components/node_modules/vuestrap/bootstrap/_button-group.scss (line 99, column 24)
 @ ./~/vuestrap/bootstrap/_button-group.scss 4:14-180

ERROR in ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./~/vuestrap-theme-loader!./~/vuestrap/bootstrap/_carousel.scss
Module build failed:
    }
     ^
      ".carousel-inner > .carousel-item > img" failed to @extend ".img-fluid".
The selector ".img-fluid" was not found.
Use "@extend .img-fluid !optional" if the extend should be able to fail.
      in ~/vuestrap-base-components/node_modules/vuestrap/bootstrap/_carousel.scss (line 21, column 7)
 @ ./~/vuestrap/bootstrap/_carousel.scss 4:14-176
```

Including those scss I added is doing it work properly.

What about including it through scss instead of javascript?

**Comment by fdionisi** [comment]
Hey man, I am not able to compile further change on `vuestrap-base-components` because of there is a style issue here.

**Comment by kzima** [comment]
What command do you use to build vuestrap-base-components and what is your webpack config file?

**Comment by fdionisi** [comment]
I'm using exactly the same build utils and configs that I found in `vuestrap-base-components`.
No changes from that point of view.

If can be helpful, my env is node 5.11.0 and npm 3.8.6

**Comment by kzima** [comment]
what command do u run?

**Comment by fdionisi** [comment]
Sorry misread the question. I tried both `npm run build` and `npm run dist`, but both are giving me the same problem

**Comment by kzima** [comment]
ok, I was able to reproduce this on clean cloned version. It must be my sass caching as it worked on my local machine no problems. I will merge your PR now. Thanks :)

**Pull request merged**
